# model python files are generated by json schema using quick type,
# see more in https://github.com/glideapps/quicktype

ReportContentFieldName = "content"
ReportMessagesInQueueFieldName = "messages_in_queue"
ReportSummaryFieldName = "summary"