# model python files are generated by json schema using quick type,
# see more in https://github.com/glideapps/quicktype
from enum import Enum


class ReportFieldName(str, Enum):
    Content = "content"
    MessagesInQueue = "messages_in_queue"
    Summary = "summary"
