name: Run Pytest with Coverage

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'main' # run code coverage only for main, release and dev
      - 'release/**/*'
      - 'dev/**/*'
  workflow_call:


jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: 123456
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
        env:
          SERVICES: sqs
          DEFAULT_REGION: us-east-1
          EDGE_PORT: 4566

    env:
      # Set environment just like the .env file
      APP_NAME: haper
      JWT_AUTH_SECRET: haper-jwt-secret-ci-test
      JWT_AUTH_COOKIE_NAME: x-haper-auth
      LOG_LEVEL: DEBUG
      POSTGRES_DSN: "" # doesn't have to set up this env as it will be replaced during pytest fixture code
      SQS_REGION: us-east-1
      SQS_ENDPOINT: "http://localhost:4566"
      SQS_QUEUE_NAME: "report-update"
      SQS_REPORT_UPDATE_QUEUE_URL: "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/$SQS_QUEUE_NAME"
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create sqs queue
        run: |
          docker exec $(docker ps --filter "ancestor=localstack/localstack" -q) \
          awslocal sqs create-queue --queue-name $SQS_QUEUE_NAME

      - name: Run Pytest with Coverage
        timeout-minutes: 5 # Timeout in 5 minutes for tests
        run: |
          # Wait until PostgreSQL is ready
          until pg_isready -h localhost -p 5432 -U user; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done
          
          # Run pytest and generate coverage report
          pytest --cov=./biz --cov=app --cov-report=xml

      - name: Upload coverage reports to Codecov
        # if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Haper-AI/haper-server